### ISSUE TITLE
Create a "unsubscribe" page for email communications

### ISSUE THREAD

**Issue by viditmaniyar** [opportunity-hack/opportunity-hack-website#4]
When receiving an email from Opportunity Hack, the receiver must the ability to opt-out of receiving emails.

**Comment by iamrudra** [comment]
Fixed by [this commit](https://github.com/opportunity-hack/opportunity-hack-website/commit/c2c67474aeaf011726c8841fdacce6b85c091b9c).

**Comment by viditmaniyar** [comment]
Fixed by [this commit](https://github.com/opportunity-hack/opportunity-hack-website/commit/c2c67474aeaf011726c8841fdacce6b85c091b9c).
